# Generated by Django 4.1.7 on 2023-04-07 12:34

from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=pdf.models.Car.generate_filename)),
                ('filename', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
            ],
        ),
    ]
