# Generated by Django 4.1.7 on 2023-04-08 07:02

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('pdf_file', models.FileField(upload_to=community.models.comment.generate_filename)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
