# Generated by Django 4.1.7 on 2023-04-08 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post_text', models.TextField()),
                ('user_post_name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
